### ISSUE TITLE
报错页面和重定向有问题

### ISSUE THREAD

**Issue by ChuckWe** [dizys/ThinkWorker#8]
报错页面和重定向在谷歌浏览器是正常的，safari以及火狐有问题
safari报的是 using HTTP/0.9,火狐是直接显示html源代码没有界面

报错信息以及跟踪信息跳转setHeader('HTTP/1.1 200 OK')才能正常

大佬能不能 给个文档 看代码看的我好蛋疼特别是数据库config。。。
两个库写发要指定key，原始文件却没有，，，

**Comment by dizys** [comment]
这个框架我已经很久很久没有更新了，我不是很建议用它。
如果只是看源码学习的话还好，真正用可能会遇到很多兼容性问题。
文档的话，我近期传上去。

**Comment by dizys** [comment]
文档上传到仓库 docs 目录下了：
https://github.com/dizys/ThinkWorker/tree/master/docs
